"use client";

import Image from "next/image";

type Section = {
  id: string;
  title: string;
  category: string;
  text: string;
  warning?: boolean;
  notice?: string;
  callout?: string;
  examples?: string[];
  related?: string[];
};

const sections: Section[] = [
  {
    id: "what-these-ai-terms-cover",
    title: "What these AI Terms cover",
    category: "SCOPE & CAPABILITIES",
    text: "These AI Terms govern your use of Talvrin’s AI-assisted features and apply together with Talvrin’s Terms of Service, Privacy Notice, Acceptable Use policy and Data Processing Addendum. They do not replace those documents — where a specific AI behavior is also addressed elsewhere, the more specific, currently approved term controls.",
    related: ["Terms of Service", "Acceptable Use"],
  },
  {
    id: "ai-assisted-features",
    title: "What Talvrin AI-assisted features are",
    category: "SCOPE & CAPABILITIES",
    warning: true,
    text: "AI-assisted features can help with discovery, organization, comparison, summarization, identifying changes and explaining relationships within the evidence Talvrin presents. These are illustrative capability categories, not a commitment that every feature is available to every account or in every market.",
    notice:
      "Talvrin has not supplied an approved AI Capability Registry describing exact feature availability by account tier or region. This page does not claim a feature is live unless Talvrin has actually released it; your product experience is the current source of truth for what is available to you.",
    examples: [
      "Searching and organizing evidence across sources, filings and market data.",
      "Summarizing or comparing related evidence at your request.",
      "Identifying and explaining changes between versions of the same evidence.",
    ],
    related: ["AI Assistance", "Platform Overview"],
  },
  {
    id: "assistance-not-evidence",
    title: "AI is assistance, not authoritative evidence",
    category: "EVIDENCE BOUNDARY",
    text: "AI should help people navigate evidence — it does not replace it. Generated output does not become authoritative simply because it reads as fluent or persuasive, and it must remain visually and semantically distinguishable from the underlying source evidence.",
    callout:
      "This is Talvrin’s core AI doctrine. Every other section of these AI Terms operates within this boundary.",
  },
  {
    id: "evidence-provenance",
    title: "Evidence, provenance and source inspection",
    category: "EVIDENCE BOUNDARY",
    text: "Where AI-assisted output relates to specific evidence, the underlying source remains separately inspectable. Review the original evidence a summary, comparison or explanation is drawn from, rather than treating the AI-generated text itself as the record.",
    related: ["Evidence", "Evidence Standards"],
  },
  {
    id: "human-judgment",
    title: "Human judgment and user responsibility",
    category: "YOUR RESPONSIBILITY",
    text: "Human judgment remains responsible for investment, professional and organizational decisions. Before relying on an AI-assisted interpretation for a material decision, inspect the underlying evidence rather than the generated summary alone.",
    examples: [
      "Inspecting underlying evidence before relying on an AI-assisted interpretation for a material decision.",
      "Treating an AI-generated explanation as a starting point for research, not a finished conclusion.",
      "Applying your own professional or organizational review process before acting on AI-assisted output.",
    ],
  },
  {
    id: "no-investment-advice",
    title: "No investment advice or trade execution",
    category: "YOUR RESPONSIBILITY",
    text: "Talvrin does not position itself as a brokerage, trade-execution service, stock-tipping service or recommendation engine — including through its AI-assisted features. Nothing generated by Talvrin’s AI constitutes investment, legal, tax or other professional advice, or a recommendation to buy, sell or hold any financial instrument. Talvrin does not promise to predict markets or eliminate uncertainty.",
    callout:
      "This boundary applies to AI-assisted output the same way it applies to the rest of Talvrin’s research and intelligence platform.",
  },
  {
    id: "accuracy-uncertainty",
    title: "Accuracy, uncertainty and completeness",
    category: "YOUR RESPONSIBILITY",
    warning: true,
    text: "AI-assisted output may be incomplete, outdated or inaccurate. Talvrin does not represent that generated summaries, comparisons or explanations are complete or error-free, and does not assign or display a numeric confidence or accuracy score for AI-assisted output.",
    notice:
      "Talvrin has not approved a methodology for quantifying AI output confidence or accuracy. Until one exists, no percentage, score or similar certainty indicator is published for AI-assisted features.",
  },
  {
    id: "prompt-input-responsibilities",
    title: "Prompt and input responsibilities",
    category: "INPUTS & OUTPUTS",
    text: "Only submit prompts or inputs you are authorized to provide, and only in ways consistent with Talvrin’s Privacy Notice, Acceptable Use policy and, where applicable, Data & Market Information Terms. Do not submit content you do not have the rights or permission to share.",
    examples: [
      "Submitting another person’s confidential or personal information without a lawful basis to do so.",
      "Pasting licensed market data or third-party content into a prompt beyond what your entitlement permits.",
      "Using prompts to attempt to extract another user’s account data or Talvrin’s internal systems.",
    ],
    related: ["Acceptable Use"],
  },
  {
    id: "output-provenance",
    title: "Output use and downstream provenance",
    category: "INPUTS & OUTPUTS",
    text: "Review AI-assisted output before reusing it, and do not misrepresent generated text as an official source, issuer statement, regulator communication or primary evidence. Where an output conflicts with the underlying evidence, the evidence record controls, subject to its own provenance and version state.",
    examples: [
      "Citing the original evidence rather than an AI-generated summary when provenance matters.",
      "Disclosing that a shared summary or comparison was AI-assisted when repurposing it outside Talvrin.",
    ],
  },
  {
    id: "privacy-data-retention",
    title: "Privacy, data handling and retention",
    category: "PRIVACY & DATA RIGHTS",
    warning: true,
    text: "Privacy, data handling and retention for AI-assisted features are governed by Talvrin’s Privacy Notice and Data Processing Addendum, not by this page. Where this page and those documents overlap, the approved Privacy Notice and Data Processing Addendum control the operative data-handling facts.",
    notice:
      "Talvrin has not published a dedicated AI data-flow registry describing prompt- and output-specific retention periods. Until one is approved, the general retention and data-handling commitments in the Privacy Notice and Data Processing Addendum apply.",
    related: ["Privacy", "Data Processing Addendum"],
  },
  {
    id: "model-providers",
    title: "Model providers and subprocessors",
    category: "PRIVACY & DATA RIGHTS",
    warning: true,
    text: "Model providers and subprocessors used to deliver AI-assisted features are disclosed here only once Talvrin approves a public model/provider record.",
    notice:
      "Talvrin has not supplied an approved AI model/provider registry for public disclosure. This page does not name a model provider, model family or version until Legal and AI Governance approve that fact for publication.",
  },
  {
    id: "training-model-improvement",
    title: "Training and model improvement",
    category: "PRIVACY & DATA RIGHTS",
    warning: true,
    text: "Whether prompts, inputs or outputs are used to train or improve Talvrin’s AI-assisted features is stated here only as an approved factual position.",
    notice:
      "Talvrin has not published an approved position on training or model-improvement use of prompts or outputs. No claim — positive or negative — is made on this page until Legal and AI Governance approve one; the Privacy Notice and Data Processing Addendum remain the controlling data-use documents in the meantime.",
  },
  {
    id: "restricted-information",
    title: "Confidential, personal and restricted information",
    category: "PRIVACY & DATA RIGHTS",
    text: "Do not submit personal data belonging to others, confidential information you are not authorized to share, or restricted content outside your entitlement as a prompt or input to an AI-assisted feature. Privacy and security rules that apply elsewhere on Talvrin apply equally to AI inputs.",
    examples: [
      "Entering a third party’s personal or health information into a prompt without a lawful basis.",
      "Submitting confidential workspace or client information beyond your authorization.",
    ],
    related: ["Privacy", "Security"],
  },
  {
    id: "market-data-rights",
    title: "Market data, licensed content and source rights",
    category: "PRIVACY & DATA RIGHTS",
    warning: true,
    text: "Licensed market data and other rights-sensitive source content remain subject to their original licensing terms when used as an AI input or reflected in AI-assisted output. Using a source as an AI prompt does not expand your rights to copy, extract or redistribute it.",
    notice:
      "Service- and dataset-specific AI rules for licensed market data are governed by Talvrin’s Data & Market Information Terms, which remain blocked pending approval of items 01–06 and this AI Terms item. Until published, your existing data license or entitlement governs.",
    related: ["Data Rights", "Acceptable Use"],
  },
  {
    id: "prohibited-ai-use",
    title: "Prohibited AI use",
    category: "GOVERNANCE & CHANGES",
    warning: true,
    text: "Do not use Talvrin’s AI-assisted features to misrepresent authorship or evidence provenance, fabricate or misattribute source material, or present AI-generated text as independently verified fact.",
    notice:
      "A complete AI-specific risk and misuse taxonomy has not yet been approved beyond the rules stated here and in Talvrin’s Acceptable Use policy. Additional prohibited-use categories publish only once Legal and AI Governance approve them.",
    examples: [
      "Presenting AI-assisted output as independently verified evidence without disclosure.",
      "Using AI features to fabricate or misattribute source material.",
      "Relying on AI-generated text as a substitute for reviewing the underlying evidence.",
    ],
    related: ["Acceptable Use"],
  },
  {
    id: "automated-decisions",
    title: "Automated decisions and high-risk use",
    category: "GOVERNANCE & CHANGES",
    warning: true,
    text: "Rules for automated-decision or high-risk AI use apply only for categories Talvrin’s Legal and AI Governance teams have specifically approved.",
    notice:
      "No automated-decision or high-risk AI use has been approved for publication on this page. Talvrin’s AI-assisted features are positioned as research assistance, not as automated decision-making authority.",
  },
  {
    id: "intellectual-property",
    title: "Intellectual property and content rights",
    category: "GOVERNANCE & CHANGES",
    warning: true,
    text: "Rights in prompts, AI-assisted outputs and related feedback are addressed here only once Legal approves a jurisdiction- and deployment-specific position.",
    notice:
      "No approved prompt/output ownership, licensing or non-infringement claim is published here. Do not infer ownership or reuse rights from the availability of AI-generated output.",
  },
  {
    id: "availability-beta",
    title: "Availability, beta and feature changes",
    category: "GOVERNANCE & CHANGES",
    text: "AI-assisted features, including any non-production or beta functionality, may change, be limited or be withdrawn consistent with Talvrin’s approved terms. A feature described as available is only as available as Talvrin’s current product release state supports.",
    callout:
      "Beta or limited-availability AI features are labeled as such in the product where applicable; this page does not promise permanence for any specific AI capability.",
  },
  {
    id: "monitoring-safety",
    title: "Monitoring and safety controls",
    category: "GOVERNANCE & CHANGES",
    warning: true,
    text: "Any monitoring or safety controls applied to AI-assisted features are described here only to the extent Talvrin has approved public disclosure of them.",
    notice:
      "Talvrin has not approved specific AI monitoring or safety-control disclosure details for publication on this page. This section does not claim that a particular monitoring mechanism is present.",
  },
  {
    id: "enforcement-suspension",
    title: "Enforcement and suspension",
    category: "GOVERNANCE & CHANGES",
    text: "Talvrin may take account-level action in response to a violation of these AI Terms or the Acceptable Use policy, consistent with the Terms of Service.",
    notice:
      "The specific enforcement actions, triggering conditions and any related review process are governed by the applicable Terms of Service and Acceptable Use policy. This section does not create a separate enforcement procedure.",
    related: ["Acceptable Use", "Terms of Service"],
  },
  {
    id: "changes-ai-terms",
    title: "Changes to these AI Terms",
    category: "GOVERNANCE & CHANGES",
    warning: true,
    text: "Talvrin may update these AI Terms as AI-assisted features, applicable law or Talvrin’s data-flow and risk registries evolve. Material changes are reflected in the version history with an updated effective date.",
    notice:
      "A public version-history view for these AI Terms is not yet available.",
  },
];

const sectionImages: Record<number, string> = {
  1: "image1.png",
  3: "image2.png",
  5: "image3.png",
  7: "image4.png",
  9: "image5.png",
  11: "image6.png",
  13: "image7.png",
  15: "image8.png",
  17: "image9.png",
  19: "image10.png",
  21: "image11.png",
};

export default function AITermsContent() {
  return (
    <section className="w-full bg-violet-50 font-['IBM_Plex_Sans',sans-serif] text-slate-900">
      <div className="mx-auto grid w-full max-w-[1440px] grid-cols-1 gap-8 px-4 sm:px-6 md:px-8 lg:grid-cols-[220px_minmax(0,1fr)] lg:gap-8 lg:px-12 lg:py-14 xl:grid-cols-[240px_minmax(0,1fr)] xl:gap-8 xl:px-20 xl:py-[72px] py-8 sm:py-10">
        {/* Table of contents */}
        <nav
          aria-label="AI Terms table of contents"
          className="min-w-0 lg:sticky lg:top-6 lg:self-start"
        >
          <div className="max-h-[220px] sm:max-h-[280px] lg:max-h-[calc(100vh-4rem)] overflow-y-auto rounded-xl border border-slate-900/10 bg-white/70 p-4 lg:rounded-none lg:border-0 lg:bg-transparent lg:p-0">
            <p className="sticky top-0 bg-white/70 lg:bg-transparent pb-1 text-xs font-bold tracking-wide text-gray-600">
              ON THIS PAGE
            </p>

            <div className="mt-2 flex flex-col gap-1">
              {sections.map((section, index) => (
                <a
                  key={section.id}
                  href={`#${section.id}`}
                  className="flex items-start gap-2 rounded-md px-2.5 py-1.5 sm:py-2 text-xs sm:text-sm leading-5 text-slate-700 transition-colors hover:bg-white hover:text-indigo-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"
                >
                  <span className="shrink-0 text-gray-500">
                    {index + 1}.
                  </span>
                  <span className="min-w-0">{section.title}</span>
                </a>
              ))}
            </div>
          </div>
        </nav>

        {/* Legal sections */}
        <div className="min-w-0">
          {sections.map((section, index) => {
            const sectionNumber = index + 1;
            const image = sectionImages[sectionNumber];

            return (
              <article
                key={section.id}
                id={section.id}
                className="min-w-0 scroll-mt-8 border-b border-slate-900/10 py-6 sm:py-8 lg:py-10 first:pt-0"
              >
                <div
                  className={
                    image
                      ? "grid min-w-0 grid-cols-1 items-start gap-6 lg:grid-cols-[minmax(0,1fr)_180px] xl:grid-cols-[minmax(0,1fr)_266px]"
                      : "min-w-0"
                  }
                >
                  {/* Section content */}
                  <div className="min-w-0">
                    <div className="mb-3 flex flex-wrap items-center gap-2">
                      <span className="rounded-full bg-indigo-500/10 px-2.5 py-1 text-[10px] sm:text-xs font-bold tracking-wide text-indigo-500">
                        {section.category}
                      </span>

                      {section.warning && (
                        <span className="rounded-full bg-yellow-600/10 px-2.5 py-1 text-[10px] sm:text-xs font-bold tracking-wide text-yellow-800">
                          NO APPROVED RULE PUBLISHED YET
                        </span>
                      )}
                    </div>

                    <h2 className="text-lg sm:text-xl font-bold leading-7 text-slate-900">
                      {sectionNumber}. {section.title}
                    </h2>

                    <p className="mt-3 break-words text-sm sm:text-base leading-6 text-slate-700">
                      {section.text}
                    </p>

                    {section.notice && (
                      <div className="mt-4 sm:mt-5 rounded-[10px] border border-yellow-600/25 bg-yellow-600/10 px-4 py-3.5">
                        <p className="break-words text-xs sm:text-sm leading-5 text-yellow-900">
                          {section.notice}
                        </p>
                      </div>
                    )}

                    {section.callout && (
                      <div className="mt-4 sm:mt-5 rounded-[10px] bg-[#171335] px-4 py-4">
                        <p className="break-words text-xs sm:text-sm leading-5 text-violet-50/90">
                          {section.callout}
                        </p>
                      </div>
                    )}

                    {section.examples && (
                      <div className="mt-4 sm:mt-5 rounded-[10px] border border-slate-900/10 bg-white p-4 sm:p-5">
                        <p className="mb-3 text-xs font-bold tracking-wide text-gray-600">
                          ILLUSTRATIVE EXAMPLES — NON-EXHAUSTIVE
                        </p>

                        <ul className="space-y-2">
                          {section.examples.map((example) => (
                            <li
                              key={example}
                              className="flex items-start gap-2.5 text-xs sm:text-sm leading-5 text-gray-600"
                            >
                              <span className="mt-2 h-[5px] w-[5px] shrink-0 rounded-full bg-yellow-600" />
                              <span className="min-w-0 break-words">
                                {example}
                              </span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {section.related && (
                      <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2">
                        <span className="text-xs font-semibold text-gray-600">
                          Related:
                        </span>

                        {section.related.map((item) => (
                          <span
                            key={item}
                            className="text-xs sm:text-sm font-semibold text-indigo-500"
                          >
                            {item} →
                          </span>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Image column: only rendered when image exists */}
                  {image && (
                    <div className="relative mx-auto aspect-[4/5] w-full max-w-[320px] overflow-hidden rounded-xl lg:mx-0 lg:max-w-none">
                      <Image
                        src={`/images/legal/ai-terms/${image}`}
                        alt={`Supporting illustration for ${section.title}`}
                        fill
                        sizes="(max-width: 639px) calc(100vw - 32px), (max-width: 1023px) min(100vw - 48px, 320px), (max-width: 1279px) 180px, 266px"
                        className="object-cover"
                      />
                    </div>
                  )}
                </div>
              </article>
            );
          })}
        </div>
      </div>
    </section>
  );
}